### PR TITLE
Fix "?" for Win10

### PR DESCRIPTION
**Pull request by mischmiko**
Fixed "? command. I am not exactly sure why this line is necessary, but it obviously immediately hides the tooltip in Win10.

### CODE REVIEW

**Comment by mischmiko** [comment]
Please also see [here](https://github.com/schmimae/Public-AutoHotKey-Scripts/blob/master/GUI/GUI.ahk#L142) for a small enhancement: Filter out commented commands.

**Comment by plul** [comment]
Hi schmimae! 

I merged your suggestions. Thanks a lot!

The last 4 lines were supposed to change the tooltip to a monospace font, and apparently the one you commented was causing a bug on Win10. One of those lines is of course needed there at the end to actually display the tooltip, even after giving up on a monospace font.

On the other hand you had a line which confused me in the middle of your loop:
-                Tooltip A_LoopReadLine, 3,3,1

This line does not do what you think it does, so I just wanted to give you a heads up. It does nothing except actually setting the text "A_LoopReadLine" on the tooltip.
The text on the tooltip should be rendered at the very end however. 

Again, thanks for your interest!

It doesn't look as nice now without the monospace font however. I'm wondering if it would be possible to simply integrate it all into the dark GUI, with a scroll bar. Maybe I will take a look at that sometime.

**Comment by mischmiko** [comment]
Hi Asger,

yes, you are right - we lost monospace, which will look ugly, but at least it works. The line "Tooltip A_LoopReadLine, 3,3,1" was indeed only for me - I tested some things as I was new to AHK :). However, I made some other enhancements (see my fork). Feel free to add any of those to your master repo. I am not good at merging changes ;-)
1. Added dynamic list of matching commands (I like it if there is only one command left, that this one gets executed automatically - might not be for everyone) - to test, just type "d"
2. Added IP address
3. Added a systray icon (made it myself, so no worries about copyright)
4. Changed uriEncode() function, as the old one did not always work
5. Slight visual change for text input (e.g. Google)
6. Do not display commented cmds in the ?-tooltip
7. Added/changes some commands, e.g.
   a. New command for calculations (e.g. 1+1) (using Calculator.ahk)
   b. New command to change sound output device
   c. New command to pause/resume Google Music or similar
   d. New command to change my Microsoft Lync status
   e. New command to open Windows Update
   f. etc.

I have seen that you made some other changes, especially for searching multiple URLs and some cleanup stuff. I did not add those changes, so you might see some differences.

Michael

Sent from my Windows Phone

**Comment by plul** [comment]
Nice! I took a quick look through your commits. I will delve more into it when I have time. 
My immediate favourite change is the simple `else gui_destroy()` for the hotstring that activates the GUI. On some occasions the GUI loses focus (when the user accidentally activates another window by clicking on it or alt-tabbing), and then it becomes necessary to refocus the GUI with the mouse. But this makes it easy to destroy it and start over. 

The calculator and dynamic display of hotkeys are nice additions. I will try to integrate those soon. 

And thanks for the icon! It was about time it got its own icon!

I have always preferred to auto-fire the hotkeys instead of waiting for the user to press `Enter`, but damn, I must say, you took it to the extreme by firing not fully typed hotkeys. :D That might be too aggressive for me, and actually I have been wondering whether I should go in the other direction and require an `Enter` as I was worried that new users would find the auto-firing off-putting. 

I have some functionality that I want to introduce on my todo list, and I am planning on cleaning it up quite a bit too and structuring it differently in the near future. 

As always, thanks for your interest in this script! :)

**Comment by mischmiko** [comment]
Yeah, absolutely - firing even incomplete commands will for sure confuse new users! Maybe it can be implemented as a simple switch in the script for users who are used to their commands.

I am also pretty sure that some of my changes can be optimized.

I will definitely watch out for new additions :)

Sent from my Windows Phone

**Pull request merged**
